/**
 Auto-generated by: angular-three-plugin:gltf
 */

import type * as THREE from 'three';
import { Group, Mesh } from 'three';
import { extend, type NgtThreeElements, NgtElementEvents, NgtObjectEvents } from 'angular-three';
import {
  Component,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  viewChild,
  ElementRef,
  inject,
  effect,
  model,
} from '@angular/core';
import { gltfResource } from 'angular-three-soba/loaders';
import type { GLTF } from 'three-stdlib';
import {
  animations,
  type NgtsAnimationClips,
  type NgtsAnimationApi,
} from 'angular-three-soba/misc';

import CloudRingGLTF from 'assets/cloud_ring-scaled.glb' with { loader: 'file' };

gltfResource.preload(CloudRingGLTF);

type ActionName = 'cloud_ring_glb';
type CloudRingAnimationClips = NgtsAnimationClips<ActionName>;
export type CloudRingAnimationApi = Exclude<
  NgtsAnimationApi<CloudRingAnimationClips>,
  { get isReady(): false }
>;

export type CloudRingGLTFGLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
  };
  materials: {
    Cloud: THREE.MeshStandardMaterial;
  };
  animations: CloudRingAnimationClips[];
};

@Component({
  selector: 'app-cloud-ring',
  template: `
    @if (gltf.value(); as gltf) {
      @let nodes = gltf.nodes;
      @let materials = gltf.materials;

      <ngt-group #model [parameters]="options()" [dispose]="null">
        <ngt-group name="cloud_ring_3glb">
          <ngt-group name="cloud_ringglb">
            <ngt-group name="Sketchfab_model" [rotation]="[-Math.PI / 2, 0, 0]">
              <ngt-group name="root">
                <ngt-group name="GLTF_SceneRootNode" [rotation]="[Math.PI / 2, 0, 0]">
                  <ngt-group name="Cloud_GN001_2">
                    <ngt-mesh
                      name="Object_4"
                      [geometry]="nodes.Object_4.geometry"
                      [material]="materials.Cloud"
                      [rotation]="[0, Math.PI / 2, 0]"
                      [scale]="[1.5, 1, 1.5]"
                    /> </ngt-group
                  ><ngt-group name="Cloud_GN002_3" [rotation]="[0, -0.016, 0]">
                    <ngt-mesh
                      name="Object_6"
                      [geometry]="nodes.Object_6.geometry"
                      [material]="materials.Cloud"
                      [scale]="[1.25, 1, 1.25]"
                    /> </ngt-group
                  ><ngt-group name="Cloud_GN003_4" [rotation]="[0, -0.031, 0]">
                    <ngt-mesh
                      name="Object_8"
                      [geometry]="nodes.Object_8.geometry"
                      [material]="materials.Cloud"
                      [rotation]="[0, Math.PI / 4, 0]"
                    />
                  </ngt-group>
                </ngt-group>
              </ngt-group>
            </ngt-group>
          </ngt-group>
        </ngt-group>

        <ng-content />
      </ngt-group>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      outputs: [
        'click',
        'dblclick',
        'contextmenu',
        'pointerup',
        'pointerdown',
        'pointerover',
        'pointerout',
        'pointerenter',
        'pointerleave',
        'pointermove',
        'pointermissed',
        'pointercancel',
        'wheel',
      ],
    },
    {
      directive: NgtElementEvents,
      outputs: ['attached', 'updated', 'created', 'disposed'],
    },
  ],
})
export class CloudRing {
  protected readonly Math = Math;

  options = input({} as Partial<NgtThreeElements['ngt-group']>);
  animations = model<CloudRingAnimationApi>();

  modelRef = viewChild<ElementRef<Group>>('model');

  protected gltf = gltfResource<CloudRingGLTFGLTFResult>(() => CloudRingGLTF);

  constructor() {
    extend({ Group, Mesh });

    // const _animations = animations(this.gltf, this.modelRef);
    // effect(() => {
    //   if (!_animations.isReady) return;
    //   this.animations.set(_animations);
    // });

    const objectEvents = inject(NgtObjectEvents, { host: true });
    const elementEvents = inject(NgtElementEvents, { host: true });

    objectEvents.events.set(this.modelRef);
    elementEvents.events.set(this.modelRef);
  }
}
